<?php

$translations = [
    // Sidebar Menu
    'Dashboard' => 'Gösterge Paneli',
    'Feedback' => 'Geri Bildirim',
    'Calender' => 'Takvim',
    'Calendar' => 'Takvim',
    'Categories' => 'Kategoriler',
    'Category' => 'Kategori',
    'User Group' => 'Kullanıcı Grubu',
    'User Groups' => 'Kullanıcı Grupları',
    'Positions' => 'Pozisyonlar',
    'Position' => 'Pozisyon',
    'Courses Management' => 'Kurs Yönetimi',
    'All Courses' => 'Tüm Kurslar',
    'Add Courses' => 'Kurs Ekle',
    'Add Course' => 'Kurs Ekle',
    'Create Course' => 'Kurs Oluştur',
    'Edit Course' => 'Kurs Düzenle',
    'View Course' => 'Kurs Görüntüle',
    'Learning Pathways Management' => 'Öğrenme Yolları Yönetimi',
    'Learning Pathways' => 'Öğrenme Yolları',
    'Contact Requests' => 'İletişim Talepleri',
    'Employee Requests' => 'Çalışan Talepleri',
    'All Reports' => 'Tüm Raporlar',
    'Site Management' => 'Site Yönetimi',
    'User Management' => 'Kullanıcı Yönetimi',
    'Settings' => 'Ayarlar',
    'General' => 'Genel',
    'Send Email Notification' => 'E-posta Bildirimi Gönder',
    'Lessons' => 'Dersler',
    'Lesson' => 'Ders',
    'Tests' => 'Sınavlar',
    'Test' => 'Sınav',
    'Certificates' => 'Sertifikalar',
    'Certificate' => 'Sertifika',
    'Certificate Issued' => 'Verilen Sertifika',
    'Bundles' => 'Paketler',
    'Orders' => 'Siparişler',
    'Coupons' => 'Kuponlar',
    'Sliders' => 'Kaydırıcılar',
    'Sponsors' => 'Sponsorlar',
    'Testimonials' => 'Referanslar',
    'FAQs' => 'SSS',
    'Reviews' => 'Değerlendirmeler',
    'Blog' => 'Blog',
    'Pages' => 'Sayfalar',
    'Menus' => 'Menüler',
    'Contacts' => 'İletişim',
    'Users' => 'Kullanıcılar',
    'Roles' => 'Roller',
    'Role' => 'Rol',
    'Permissions' => 'İzinler',
    'Permission' => 'İzin',
    'Log Viewer' => 'Günlük Görüntüleyici',
    'Activity' => 'Aktivite',
    'Access' => 'Erişim',
    'Language' => 'Dil',

    // Dashboard
    'Welcome' => 'Hoş Geldiniz',
    'Active Users' => 'Aktif Kullanıcılar',
    'Added Courses' => 'Eklenen Kurslar',
    'Assigned Users' => 'Atanan Kullanıcılar',
    'Assignments' => 'Ödevler',
    'Assignment' => 'Ödev',
    'Average Completion Rate' => 'Ortalama Tamamlanma Oranı',
    'Average Assessment Score' => 'Ortalama Değerlendirme Puanı',
    'Latest Course Assignments' => 'Son Kurs Atamaları',
    'Recent Courses (Last 10 Created)' => 'Son Kurslar (Son 10)',
    'Recent Courses' => 'Son Kurslar',
    'Filter Your Progress' => 'İlerlemenizi Filtreleyin',
    'Completed' => 'Tamamlandı',
    'Remaining' => 'Kalan',
    'No courses yet.' => 'Henüz kurs yok.',
    'No courses yet' => 'Henüz kurs yok',
    'No recent course assignments.' => 'Son kurs ataması yok.',
    'No recent course assignments' => 'Son kurs ataması yok',
    'View All' => 'Tümünü Gör',

    // User & Auth
    'Login' => 'Giriş Yap',
    'Logout' => 'Çıkış',
    'Register' => 'Kayıt Ol',
    'Profile' => 'Profil',
    'Account' => 'Hesap',
    'My Account' => 'Hesabım',
    'Messages' => 'Mesajlar',
    'Notifications' => 'Bildirimler',
    'Mark All As Read' => 'Tümünü Okundu İşaretle',
    'No new notifications' => 'Yeni bildirim yok',
    'View All Notifications' => 'Tüm Bildirimleri Gör',
    'No messages' => 'Mesaj yok',
    'Administration' => 'Yönetim',
    'First Name' => 'Ad',
    'Last Name' => 'Soyad',
    'Email' => 'E-posta',
    'Password' => 'Şifre',
    'Confirm Password' => 'Şifre Tekrar',
    'Remember Me' => 'Beni Hatırla',
    'Forgot Password' => 'Şifremi Unuttum',
    'Reset Password' => 'Şifre Sıfırla',
    'Send Password Reset Link' => 'Şifre Sıfırlama Bağlantısı Gönder',
    'Active Users' => 'Aktif Kullanıcılar',
    'Deactivated Users' => 'Deaktif Kullanıcılar',
    'Deleted Users' => 'Silinen Kullanıcılar',
    'Create User' => 'Kullanıcı Oluştur',
    'Edit User' => 'Kullanıcı Düzenle',

    // Buttons & Actions
    'Save' => 'Kaydet',
    'Save Settings' => 'Ayarları Kaydet',
    'Update' => 'Güncelle',
    'Cancel' => 'İptal',
    'Delete' => 'Sil',
    'Create' => 'Oluştur',
    'Edit' => 'Düzenle',
    'View' => 'Görüntüle',
    'Back' => 'Geri',
    'Submit' => 'Gönder',
    'Search' => 'Ara',
    'Filter' => 'Filtrele',
    'Export' => 'Dışa Aktar',
    'Import' => 'İçe Aktar',
    'Download' => 'İndir',
    'Upload' => 'Yükle',
    'Actions' => 'İşlemler',
    'Yes' => 'Evet',
    'No' => 'Hayır',
    'Select' => 'Seç',
    'Select One' => 'Birini Seç',
    'All' => 'Tümü',
    'Total' => 'Toplam',
    'Close' => 'Kapat',
    'Confirm' => 'Onayla',
    'Add' => 'Ekle',
    'Remove' => 'Kaldır',
    'Next' => 'İleri',
    'Previous' => 'Önceki',
    'Done' => 'Tamamlandı',

    // Course Related
    'Title' => 'Başlık',
    'Course Title' => 'Kurs Başlığı',
    'Course Code' => 'Kurs Kodu',
    'Course Name' => 'Kurs Adı',
    'Course Category' => 'Kurs Kategorisi',
    'Course Assignment' => 'Kurs Ataması',
    'Description' => 'Açıklama',
    'Short Description' => 'Kısa Açıklama',
    'Image' => 'Resim',
    'Name' => 'Ad',
    'Date' => 'Tarih',
    'Price' => 'Fiyat',
    'Free' => 'Ücretsiz',
    'Type' => 'Tür',
    'Status' => 'Durum',
    'Duration' => 'Süre',
    'Start Date' => 'Başlangıç Tarihi',
    'End Date' => 'Bitiş Tarihi',
    'Start Time' => 'Başlangıç Zamanı',
    'End Time' => 'Bitiş Zamanı',
    'Published' => 'Yayında',
    'Unpublished' => 'Yayında Değil',
    'Draft' => 'Taslak',
    'Pending' => 'Beklemede',
    'Approved' => 'Onaylandı',
    'Rejected' => 'Reddedildi',
    'Active' => 'Aktif',
    'Inactive' => 'Pasif',
    'Enabled' => 'Etkin',
    'Disabled' => 'Devre Dışı',
    'Featured' => 'Öne Çıkan',
    'Trending' => 'Trend',
    'Popular' => 'Popüler',
    'Teacher' => 'Eğitmen',
    'Teachers' => 'Eğitmenler',
    'Instructor' => 'Eğitmen',
    'Student' => 'Öğrenci',
    'Students' => 'Öğrenciler',
    'Trainer Name' => 'Eğitmen Adı',
    'Questions' => 'Sorular',
    'Question' => 'Soru',
    'Options' => 'Seçenekler',
    'Correct Answer' => 'Doğru Cevap',
    'Score' => 'Puan',
    'Progress' => 'İlerleme',
    'Enrollment' => 'Kayıt',
    'Manage Lessons' => 'Dersleri Yönet',
    'Add Lesson' => 'Ders Ekle',

    // Reports & Employee
    'Department' => 'Departman',
    'Employee Type' => 'Çalışan Tipi',
    'Gender' => 'Cinsiyet',
    'Nationality' => 'Uyruk',
    'Date of birth' => 'Doğum Tarihi',
    'Mobile phone' => 'Cep Telefonu',
    'Assessment' => 'Değerlendirme',
    'Attendance' => 'Katılım',
    'Report' => 'Rapor',
    'Reports' => 'Raporlar',
    'Feedback Questions' => 'Geri Bildirim Soruları',
    'News & Update' => 'Haberler ve Güncellemeler',
    'Updates' => 'Güncellemeler',
    'Events' => 'Etkinlikler',
    'Libraries' => 'Kütüphane',
    'Announcement' => 'Duyurular',
    'News'    => 'Haberler',
    'User Assignment' => 'Kullanıcı Ataması',

    // Frontend
    'Home' => 'Ana Sayfa',
    'About Us' => 'Hakkımızda',
    'Contact Us' => 'Bize Ulaşın',
    'Our Mission' => 'Misyonumuz',
    'Our Vision' => 'Vizyonumuz',
    'Quick Links' => 'Hızlı Bağlantılar',
    'Get In Touch' => 'İletişime Geçin',
    'Terms & Conditions' => 'Şartlar ve Koşullar',
    'Privacy Policy' => 'Gizlilik Politikası',
    'Get Help' => 'Yardım Al',
    'Become a Teacher' => 'Eğitmen Ol',
    'Search for course' => 'Kurs ara',
    'Browse All' => 'Tümüne Göz At',
    'Learn More' => 'Daha Fazla',
    'Popular Courses' => 'Popüler Kurslar',
    'Latest Events' => 'Son Etkinlikler',
    'News & Updates' => 'Haberler ve Güncellemeler',
    'Create Account' => 'Hesap Oluştur',
    'SignUp' => 'Kaydol',
    'Copyright' => 'Telif Hakkı',
    'All Rights Reserved' => 'Tüm Hakları Saklıdır',
    'App Name' => 'Uygulama Adı',

    // Alerts
    'successfully created' => 'başarıyla oluşturuldu',
    'successfully updated' => 'başarıyla güncellendi',
    'successfully deleted' => 'başarıyla silindi',
    'successfully restored' => 'başarıyla geri yüklendi',
    'Successfully' => 'Başarıyla',
    'successfully' => 'başarıyla',

    // Internal/External
    'Internal' => 'Dahili',
    'External' => 'Harici',
    'internal' => 'Dahili',
    'external' => 'Harici',
    'general' => 'Genel',
];

// Files to translate
$files = glob(__DIR__ . '/resources/lang/tr/*.php');

$count = 0;
foreach ($files as $file) {
    $content = file_get_contents($file);
    $original = $content;

    foreach ($translations as $en => $tr) {
        $content = str_replace("=> '$en'", "=> '$tr'", $content);
        $content = str_replace("=> \"$en\"", "=> \"$tr\"", $content);
        $content = str_replace("=> '$en',", "=> '$tr',", $content);
        $content = str_replace("=> \"$en\",", "=> \"$tr\",", $content);
    }

    if ($content !== $original) {
        file_put_contents($file, $content);
        $count++;
        echo "Translated: " . basename($file) . "\n";
    }
}

echo "\nDone! $count files translated.\n";